export const GetGeneralData = '/getData'
export const GetResInfoData = '/GetResInfoData'
export const GetAuctionData = '/getAuctionData'
export const GetUserAddress = '/getAllIds'
export const GetUserBaseInfo = '/getUserInfo'
export const SendMails = '/sendMails'
export const MailsHistroy = '/getMailBySender'
